const Database = [
  { name: 'immutable-js', private: false, sources: false, forks: true },
  { name: 'cortex', private: false, sources: false, forks: true },
  // { name: 'avers', private: false, sources: false, forks: true },
  // { name: 'imvvm', private: false, sources: false, forks: true },
  // { name: 'moreartyjs', private: false, sources: false, forks: true },
  // { name: 'valuable', private: false, sources: false, forks: true },
  // { name: 'react-resolver', private: false, sources: false, forks: true },
  // { name: 'freezer-js', private: false, sources: false, forks: true },
  // { name: 'mobx', private: false, sources: false, forks: true },
  // { name: 'baobab-react', private: false, sources: false, forks: true },
  // { name: 'datascript', private: false, sources: false, forks: true },
  // { name: 'immstruct', private: false, sources: false, forks: true },
  // { name: 'seamless-immutable', private: false, sources: false, forks: true },
  // { name: 'tydel', private: false, sources: false, forks: true },
  // { name: 'extendable-immutable', private: false, sources: true, forks: false },
  // { name: 'learn-git-basics', private: true, sources: true, forks: false },
  // { name: 'custom-video-player', private: false, sources: true, forks: false },
  // { name: 'svg-animation-react', private: false, sources: true, forks: false },
  // { name: 'tour-de-css-animated-logo', private: false, sources: true, forks: false },
  // { name: 'shapes-animated-svg-logo', private: false, sources: true, forks: false },
  // { name: 'render-html-with-vanilla-js', private: false, sources: true, forks: false },
  // { name: 'countdown-clock', private: false, sources: true, forks: false },
  // { name: 'layout-without-flexbox', private: true, sources: true, forks: false },
  // { name: 'video-speed-controller', private: false, sources: true, forks: false },
  // { name: 'click-drag-scroll', private: false, sources: true, forks: false },
  // { name: 'sticky-nav', private: true, sources: true, forks: false },
  // { name: 'text-to-voice-app', private: true, sources: true, forks: false },
  // { name: 'articles-app', private: false, sources: true, forks: false },
  // { name: 'speech-recognition-app', private: true, sources: true, forks: false },
  // { name: 'css-follows-mouse', private: false, sources: true, forks: false },
  // { name: 'webcam-app', private: false, sources: true, forks: false },
  // { name: 'save-favourites-react', private: true, sources: true, forks: false },
  // { name: 'react-note-taking-app', private: false, sources: true, forks: false },
  // { name: 'development-environment-setup', private: false, sources: true, forks: false },
  // { name: 'custom-video-player-react', private: true, sources: true, forks: false },
  // { name: 'slide-in-images-on-scroll', private: false, sources: true, forks: false },
  // { name: 'reach-the-treasure-game', private: false, sources: true, forks: false },
  // { name: 'create-react-app', private: false, sources: true, forks: false },
  // { name: 'social-skills-hero', private: true, sources: true, forks: false },
  // { name: 'chat-app-node', private: false, sources: true, forks: false },
  // { name: 'todo-app-node', private: false, sources: true, forks: false },
  // { name: 'mocha-testing-playground-node', private: false, sources: true, forks: false },
  // { name: 'weather-app-node', private: true, sources: true, forks: false },
  // { name: 'notes-app-node', private: false, sources: true, forks: false },
  // { name: 'drawing-app-react', private: true, sources: true, forks: false },
  // { name: 'what-a-wonderful-world', private: false, sources: true, forks: false },
  // { name: 'watch-react', private: false, sources: true, forks: false },
  // { name: 'drum-kit-react', private: false, sources: true, forks: false },
  // { name: 'watch-vanilla-javascript', private: false, sources: true, forks: false },
  // { name: 'flexbox-visual-guide', private: false, sources: true, forks: false },
  // { name: 'drum-kit-vanilla-javascript', private: true, sources: true, forks: false },
  // { name: 'codewar-katas', private: false, sources: true, forks: false },
  // { name: 'online-course-app', private: false, sources: true, forks: false },
  // { name: 'udacity-github-course', private: true, sources: true, forks: false },
  // { name: 'resources-react-native', private: false, sources: true, forks: false },
  // { name: 'albums-app-react-native', private: true, sources: true, forks: false },
  // { name: 'react-video-player', private: false, sources: true, forks: false },
  // { name: 'restaurant-tip-calculator', private: false, sources: true, forks: false }
];

export default Database;
